server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5434/taxifleet
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

jwt.secret=taxifleet-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

logging.level.ru.taxifleet=INFO
logging.level.org.springframework.security=WARN